# Generated by Django 3.1 on 2020-08-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='overview',
            field=models.TextField(default='/media/image/placeholder.jpg'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.JSONField(),
        ),
    ]
