# Generated by Django 3.1 on 2020-08-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200815_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(error_messages={'unique': 'The article title is already used'}, max_length=500, unique=True),
        ),
    ]
