# Generated by Django 3.1.1 on 2020-09-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200815_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='overview',
            field=models.TextField(default='/media/images/placeholder.jpg'),
        ),
    ]
